# Generated by Django 6.0.2 on 2026-02-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_slotpricing_options_remove_booking_qr_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
